name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm install -g electron-packager
    - run: electron-packager . digiOH-3D-Viewer --platform=win32 --arch=x64
      env:
        CI: true
    - name: Zip Artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./DigiOH-3D-Viewer.zip ./digiOH-3D-Viewer-win32-x64
